### ISSUE TITLE
Please don't use racist malware as a dependency of this.

### ISSUE THREAD

**Issue by Turtgun** [ktwrd/toolbox#1]
You are using peacenotwar as a dependency in which the package literally wipes one's computers with heart emojis if they live in Russia or Belarus. This package is not protestware but targeted malware onto a group, one in which doesn't want the war and are suffering from it. Allegedly, even American NGO has been affected by this due to using Russian VPNs, deleting around 30,000 files from whistleblowers and losing quite a lot information.

Once again, your dependency is malware, not anything else.

**Comment by ktwrd** [comment]
It was a dependency for less than 48 hours. Calm your farm!
